#' @title Draw an exploratory treemap
#' @export
#' @family treemapify
#'
#' @description
#'
#' Takes a data frame of treemap coordinates produced by "treemapify" and
#' draws an exploratory treemap.  The output is a ggplot2 plot, so it can
#' be further manipulated e.g. a title added.
#'
#' @param treeMap A data frame of treemap coordinates produced by
#' "treemapify"
#' @param label.colour Colour for individual rect labels; defaults to white
#' @param label.type How the labels should be drawn inside each rect. ‘shrink’
#' (default) will cause the labels to be drawn at ‘label.size’, unless that
#' would make them too big for the rects, in which case they are shrunk to fit
#' the rects. ‘fill’ draws the labels at the largest possible size for their
#' rects. See documentation for the \code{ggfittext} package for more details.
#' @param label.size Size for individual rect labels, in points. Defaults to 24
#' pt.
#' @param label.min.size Any label shrunk below this size (in points) will not
#' be drawn. Defaults to 4 pt.
#' @param label.place Where in the rect should the label be drawn? Defaults to
#' ‘topleft’, unless label.type is ‘fill’ in which case defaults to ‘middle’.
#' See \code{ggfittext} documentation for more details.
#' @param rect.border.colour Colour for the borders between rects. Defaults to
#' grey.
#' @param rect.border.size Size (line thickness) for the borders between rects.
#' Defaults to 0.2.
#' @param group.labels Logical indicating whether groups should be labeled.
#' Defaults to TRUE.
#' @param group.label.colour Colour for group labels. Defaults to grey20.
#' @param group.label.type How the group labels should be drawn inside each
#' group. ‘shrink’ (default) will cause the labels to be drawn at ‘label.size’,
#' unless that would make them too big for the rects, in which case they are
#' shrunk to fit the rects. ‘fill’ draws the labels at the largest possible size
#' for their rects. See documentation for the \code{ggfittext} package for more
#' details.
#' @param group.label.size Size for group labels, in points. Defaults to 36 pt.
#' @param group.label.min.size Any group label shrunk below this size (in
#' points) will not be drawn. Defaults to 4 pt.
#' @param group.label.place Where in the group should the group label be drawn?
#' Defaults to ‘bottom’, unless group.label.type is ‘fill’ in which case
#' defaults to ‘middle’. See \code{ggfittext} documentation for more details.
#' @param group.border.colour Colour for borders around groups. Defaults to
#' grey50.
#' @param group.border.size Size (line thickness) for borders around groups.
#' Defaults to 1.2.
ggplotify <- function(
  treeMap,
  label.colour = "white",
  label.type = "shrink",
  label.size = 24,
  label.min.size = 4,
  label.place = NULL,
  rect.border.colour = "grey",
  rect.border.size = 0.2,
  group.labels = TRUE,
  group.label.colour = "grey20",
  group.label.type = "shrink",
  group.label.size = 36,
  group.label.min.size = 4,
  group.label.place = NULL,
  group.border.colour = "grey50",
  group.border.size = 1.2
) {

  # Check that label.type is a recognised type
  if (!label.type %in% c("shrink", "fill")) {
    stop("Unrecognised value ‘", label.type, "’ for label.type", call. = F)
  }

  # If no argument for label.place provided, set based on label.type
  if (is.null(label.place)) {
    label.place <- ifelse(label.type == "shrink", "topleft", "middle")
  }

  # Check that group.label.type is a recognised type
  if (!group.label.type %in% c("shrink", "fill")) {
    stop("Unrecognised value ‘", group.label.type, "’ for group.label.type", call. = F)
  }

  # If no argument for group.label.place provided, set based on group.label.type
  if (is.null(group.label.place)) {
    group.label.place <- ifelse(group.label.type == "shrink", "bottom", "middle")
  }

  # Determine limits of plot area (usually 100x100)
  xlim <- c(min(treeMap["xmin"]), max(treeMap["xmax"]))
  ylim <- c(min(treeMap["ymin"]), max(treeMap["ymax"]))

  # Set up plot area
  Plot <- ggplot(treeMap)
  Plot <- Plot + coord_cartesian(xlim = xlim, ylim = ylim)

  # Add rects generated by treemapify
  Plot <- Plot + geom_rect(aes(
    xmin = xmin,
    xmax = xmax,
    ymin = ymin,
    ymax = ymax,
    fill = fill
  ))

  # Add borders for individual rects
  Plot <- Plot + geom_rect(aes(
    xmin = xmin,
    xmax = xmax,
    ymin = ymin,
    ymax = ymax
  ), fill = NA, colour = rect.border.colour, size = rect.border.size)

  # Blank out extraneous plot elements
  Plot <- Plot + theme(
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank()
  )

  # Draw legend
  Plot <- Plot + guides(
    fill = guide_legend(title = attributes(treeMap)$fillName)
  )

  # If the rects are grouped, add a nice border around each group
  if ("group" %in% colnames(treeMap)) {

    # Determine x and y extents for each group
    groupRects <- ddply(
      treeMap,
      .(group),
      summarise,
      xmin <- min(xmin),
      xmax <- max(xmax),
      ymin <- min(ymin),
      ymax <- max(ymax)
    )
    names(groupRects) <- c("group", "xmin", "xmax", "ymin", "ymax")

    # Add group borders to plot
    Plot <- Plot + geom_rect(
      data = groupRects,
      mapping = aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      colour = group.border.colour,
      fill = NA,
      size = group.border.size
    )
  }

  # Add group labels, if asked to
  if (group.labels && "group" %in% colnames(treeMap)) {

    groupLabels <- ddply(
      treeMap,
      c("group"),
      summarise,
      xmin = min(xmin),
      xmax = max(xmax),
      ymin = min(ymin),
      ymax = max(ymax)
    )

    # Add group labels to plot
    Plot <- Plot + geom_fit_text(
      data = groupLabels,
      aes(label = group, xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      place = group.label.place,
      padding.y = unit(2, "mm"),
      size = group.label.size,
      min.size = group.label.min.size,
      colour = group.label.colour,
      fill.text = group.label.type == "fill"
    )
  }

  # Add labels for individual rects, if they are present
  if ("label" %in% colnames(treeMap)) {

    Plot <- Plot + geom_fit_text(
      data = treeMap,
      aes(
        label = label,
        xmin = xmin,
        xmax = xmax,
        ymin = ymin,
        ymax = ymax,
      ),
      size = label.size,
      colour = label.colour,
      min.size = label.min.size,
      place = label.place,
      padding.y = unit(1, "mm"),
      fill.text = label.type == "fill"
    )
  }

  return(Plot)
}
